name: align-vae
channels:
  - pytorch
  - conda-forge
dependencies:
  - blas=2.116
  - blas-devel=3.9.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.12.7
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.1.1
  - contourpy=1.0.7
  - cryptography=39.0.2
  - cycler=0.11.0
  - ffmpeg=4.3
  - filelock=3.10.0
  - fonttools=4.39.2
  - freetype=2.12.1
  - gettext=0.21.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.13
  - idna=3.4
  - importlib-resources=5.12.0
  - importlib_resources=5.12.0
  - jinja2=3.1.2
  - jpeg=9e
  - kiwisolver=1.4.4
  - lame=3.100
  - lcms2=2.15
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcxx=15.0.7
  - libdeflate=1.17
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=12.2.0
  - libiconv=1.17
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libpng=1.6.39
  - libsqlite=3.40.0
  - libtiff=4.5.0
  - libwebp-base=1.3.0
  - libxcb=1.13
  - libzlib=1.2.13
  - llvm-openmp=15.0.7
  - markupsafe=2.1.2
  - matplotlib=3.7.1
  - matplotlib-base=3.7.1
  - mkl=2022.1.0
  - mkl-devel=2022.1.0
  - mkl-include=2022.1.0
  - mpc=1.3.1
  - mpfr=4.2.0
  - mpmath=1.3.0
  - munkres=1.1.4
  - ncurses=6.3
  - nettle=3.6
  - networkx=3.0
  - numpy=1.24.2
  - openh264=2.1.1
  - openjpeg=2.5.0
  - openssl=3.1.0
  - packaging=23.0
  - pandas=1.5.3
  - patsy=0.5.3
  - pillow=9.4.0
  - pip=23.0.1
  - platformdirs=3.1.1
  - pooch=1.7.0
  - pthread-stubs=0.4
  - pycparser=2.21
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.8.16
  - python-dateutil=2.8.2
  - python_abi=3.8
  - pytorch=2.0.0
  - pytz=2022.7.1
  - readline=8.1.2
  - requests=2.28.2
  - scipy=1.10.1
  - seaborn=0.12.2
  - seaborn-base=0.12.2
  - setuptools=67.6.0
  - six=1.16.0
  - statsmodels=0.13.5
  - sympy=1.11.1
  - tbb=2021.8.0
  - tk=8.6.12
  - torchvision=0.15.0
  - tornado=6.2
  - typing-extensions=4.5.0
  - typing_extensions=4.5.0
  - unicodedata2=15.0.0
  - urllib3=1.26.15
  - wheel=0.40.0
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - zipp=3.15.0
  - zlib=1.2.13
  - zstd=1.5.2
prefix: /Users/ayesha/opt/anaconda3/envs/align-vae
